export const GET_CURRENCY_DATA = 'GET_CURRENCY_DATA';
export const GET_CURRENCY_CONVERSION_DATA = 'GET_CURRENCY_CONVERSION_DATA';
export const TOGGLE_ERROR = 'TOGGLE_ERROR';
export const CHANGE_HANDLER = 'CHANGE_HANDLER';
